# Generated by Django 6.0 on 2026-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performer', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('Lenght', models.FloatField()),
                ('Path', models.CharField(max_length=50)),
            ],
        ),
    ]
