# Generated by Django 6.0 on 2026-01-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidmixer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='Lenght',
            new_name='Length',
        ),
    ]
