# Generated by Django 6.0 on 2026-01-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidmixer', '0002_rename_lenght_music_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='Length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='Path',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='Performer',
            new_name='performer',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='Title',
            new_name='title',
        ),
    ]
