# Generated by Django 6.0 on 2026-04-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidmixer', '0003_rename_length_music_length_rename_path_music_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('bpm', models.IntegerField()),
                ('fade', models.IntegerField()),
                ('track_count', models.IntegerField(default=0)),
                ('playlist_snapshot', models.TextField(blank=True, null=True)),
                ('output_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='music',
            old_name='length',
            new_name='bpm',
        ),
    ]
