# Generated by Django 6.0 on 2026-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidmixer', '0004_mixgeneration_rename_length_music_bpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='performer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
