# Generated by Django 6.0 on 2026-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidmixer', '0005_alter_music_bpm_alter_music_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='end_mix_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='start_mix_point',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
