# Generated by Django 6.0 on 2026-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidmixer', '0006_music_end_mix_point_music_start_mix_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixgeneration',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
