# Generated by Django 6.0 on 2026-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidmixer', '0007_mixgeneration_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='end_mix_point',
        ),
        migrations.RemoveField(
            model_name='music',
            name='start_mix_point',
        ),
        migrations.AlterField(
            model_name='music',
            name='bpm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
